version: "3"
services:
  master:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database1
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
    volumes:
      - ./configs/master.cnf:/etc/mysql/conf.d/master.cnf
    ports:
      - 3306:3306

  slave1:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database2
      MYSQL_USER: user2
      MYSQL_PASSWORD: password2
    volumes:
      - ./configs/slave1.cnf:/etc/mysql/conf.d/slave1.cnf
    ports:
      - 3307:3306
