version: "3"
services:
  primary:
    image: mysql/mysql-server:8.0
    hostname: primary
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database1
    volumes:
      - ./configs/primary.cnf:/root/.my.cnf
      - ./scripts/primary.sql:/docker-entrypoint-initdb.d/primary.sql
    ports:
      - 3306:3306

  secondary1:
    image: mysql/mysql-server:8.0
    hostname: secondary1
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database1
    volumes:
      - ./configs/secondary1.cnf:/root/.my.cnf
      - ./scripts/secondary.sql:/docker-entrypoint-initdb.d/secondary.sql
    ports:
      - 3307:3306

  secondary2:
    image: mysql/mysql-server:8.0
    hostname: secondary2
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database1
    volumes:
      - ./configs/secondary2.cnf:/root/.my.cnf
      - ./scripts/secondary.sql:/docker-entrypoint-initdb.d/secondary.sql
    ports:
      - 3308:3306
