version: "3"
services:
  mysql-shell:
    image: neumayer/mysql-shell-batch
    environment:
      MYSQL_USER: root
      MYSQL_HOST: primary
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: root_password
      MYSQLSH_SCRIPT: /scripts/setupCluster.js
    volumes:
      - ./scripts/:/scripts/
    depends_on:
      - primary
      - secondary1
      - secondary2

  mysql-router:
    image: mysql/mysql-router:8.0
    environment:
      MYSQL_USER: root
      MYSQL_HOST: primary
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: root_password
      MYSQL_INNODB_NUM_MEMBERS: 3
    ports:
      - "6446:6446"
    depends_on:
      - primary
      - secondary1
      - secondary2
      - mysql-shell
    restart: on-failure

  primary:
    image: mysql/mysql-server:8.0.12
    hostname: primary
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database1
    ports:
      - "3301:3306"
    volumes:
      - ./configs/master.cnf:/root/.my.cnf

  secondary1:
    image: mysql/mysql-server:8.0.12
    hostname: secondary1
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database1
    ports:
      - "3302:3306"
    volumes:
      - ./configs/slave1.cnf:/root/.my.cnf

  secondary2:
    image: mysql/mysql-server:8.0.12
    hostname: secondary2
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database1
    ports:
      - "3303:3306"
    volumes:
      - ./configs/slave2.cnf:/root/.my.cnf
