version: "3"
services:
  primary:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database1
    volumes:
      - ./configs/primary.cnf:/etc/mysql/conf.d/primary.cnf
      - ./scripts/primary.sql:/docker-entrypoint-initdb.d/primary.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
    ports:
      - 3306:3306

  secondary1:
    image: mysql:8.4.0
    restart: always
    depends_on:
      primary:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database1
    volumes:
      - ./configs/secondary1.cnf:/etc/mysql/conf.d/secondary1.cnf
      - ./scripts/secondary1.sql:/docker-entrypoint-initdb.d/secondary1.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
    ports:
      - 3307:3306

  secondary2:
    image: mysql:8.4.0
    restart: always
    depends_on:
      secondary1:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database1
    volumes:
      - ./configs/secondary2.cnf:/etc/mysql/conf.d/secondary2.cnf
      - ./scripts/secondary2.sql:/docker-entrypoint-initdb.d/secondary2.sql
    ports:
      - 3308:3306
