version: "3"
services:
  master:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database1
    volumes:
      - ./configs/master.cnf:/etc/mysql/conf.d/master.cnf
      - ./scripts/master.sql:/docker-entrypoint-initdb.d/master.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
    ports:
      - 3306:3306

  slave1:
    image: mysql:8.4.0
    depends_on:
      master:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database1
    volumes:
      - ./configs/slave1.cnf:/etc/mysql/conf.d/slave1.cnf
      - ./scripts/slave1.sql:/docker-entrypoint-initdb.d/slave1.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
    ports:
      - 3307:3306

  slave2:
    image: mysql:8.4.0
    depends_on:
      slave1:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database1
    volumes:
      - ./configs/slave2.cnf:/etc/mysql/conf.d/slave2.cnf
      - ./scripts/slave2.sql:/docker-entrypoint-initdb.d/slave2.sql
    ports:
      - 3308:3306
